# Generated by Django 5.2.8 on 2025-12-03 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_class_ref_alter_parentprofile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='الرابط المرتبط')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('type', models.CharField(choices=[('ASSIGNMENT', 'واجب جديد'), ('GRADE', 'درجة جديدة'), ('ANNOUNCEMENT', 'إعلان عام'), ('ALERT', 'تنبيه')], default='ANNOUNCEMENT', max_length=20, verbose_name='النوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ('-created_at',),
            },
        ),
    ]
