# Generated by Django 5.2.8 on 2025-12-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع التقييم')),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='الوزن النسبي في المعدل العام للمادة')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نوع السلوك')),
                ('is_positive', models.BooleanField(default=False, verbose_name='إيجابي؟')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط المكتسبة/المفقودة')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(max_length=100, verbose_name='اسم المدير')),
                ('secretary_name', models.CharField(max_length=100, verbose_name='اسم أمين السر')),
            ],
            options={
                'verbose_name': 'معلومات المدرسة',
                'verbose_name_plural': 'معلومات المدرسة',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_guidance_counselor',
            field=models.BooleanField(default=False, verbose_name='موجه طلابي'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='مدير المدرسة'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='أمين السر'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assessment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessmenttype', verbose_name='تصنيف التقييم'),
        ),
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('points_change', models.IntegerField(editable=False, verbose_name='تغيير النقاط')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='سجله المدرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='core.student', verbose_name='الطالب')),
                ('behavior_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.behaviortype', verbose_name='نوع السلوك')),
            ],
        ),
    ]
